name: cyber_map
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  file_picker: 8.0.3
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.6
  flutter_compass: 
    git: https://github.com/hemanthrajv/flutter_compass.git
  flutter_dotenv: ^5.1.0
  flutter_map: 6.1.0
  flutter_map_animations: 0.6.0
  flutter_map_marker_cluster: 1.3.6
  flutter_secure_storage: 9.1.1
  flutter_svg: 2.0.10+1
  get_it: 7.7.0
  google_fonts: 6.2.1
  http: 1.2.1
  injectable: 2.4.0
  intl: 0.19.0
  latlong2: 0.9.1
  location:
    git:
      url: https://github.com/Lyokone/flutterlocation.git
      path: packages/location

  mbtiles: 0.4.1
  path_provider: ^2.1.3
  routing_client_dart:
      git:
        url: https://github.com/baconjuggling/OSM-Routing-Client-Dart.git
        ref: main
  sqflite: 2.3.3+1
  sqlite3_flutter_libs: 0.5.21
  vector_map_tiles_mbtiles: 1.1.0
  vector_tile: 2.0.0
  xml: 6.5.0

dev_dependencies:
  build_runner: 2.4.9

  flutter_test:
    sdk: flutter

  injectable_generator: 2.6.1
  lint: 2.3.0

flutter:
  uses-material-design: true
  assets:
    - assets/icons/
    - .env  
